---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: downloader
  labels:
    app.kubernetes.io/name: lidarr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidarr
    spec:
      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:2.14.5
          env:
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1002"
            - name: TZ
              value: Europe/Berlin
          ports:
            - containerPort: 8686
              name: http
          volumeMounts:
            - name: config-vol
              mountPath: /config
            - name: music-vol
              mountPath: /vol_raidz1/music
      nodeSelector:
        node-role/workload: zfs
      restartPolicy: Always
      volumes:
        - name: config-vol
          hostPath:
            path: /vol_raidz1/container-scheduler/downloader-lidarr
            type: DirectoryOrCreate
        - name: music-vol
          hostPath:
            path: /vol_raidz1/music
            type: Directory
