---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: downloader

commonAnnotations:
  argocd.argoproj.io/sync-wave: "64"

resources:
  - k8s.deployment.yaml
  - k8s.service.yaml
  - k8s.np.downloader-lidarr.yaml

generators:
  - kustomize-secret-generator.yaml
