apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: epicgames-freegames
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "30"
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
    ingressClassName: traefik
    tls:
        - hosts:
            - ENC[AES256_GCM,data:XQak67WwXmNYPnjKmDCncE1fny6F,iv:PNz7e4kJsUqGetdo5p9NiDq4hQ7jQ1vdoqJU9JYsjNo=,tag:nmJbJKRrw5pXxIcW+gu78w==,type:str]
          secretName: wildcard-cloudflare-production-01
    rules:
        - host: ENC[AES256_GCM,data:aDq2J5n9pMaKKiQKS3dNkbot1BXA,iv:0J4tUaDc1g8LU54dKcPWD1dcay1RmU/kuNTXn0PjyJ8=,tag:ciblQQbCkqK04YnSsvlcXQ==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: epicgames-freegames
                        port:
                            number: 3000
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTHh1T2JHSlFXNnN1UkFp
            NFNGRGRZN3g5eXYySEE5Tjh0bGtabkU3OW1RClA5VUtVRGVaU0dBVlZSTWptaVlp
            dzFueHNZaVRmVEwwMmVDVzdVanFVaTAKLS0tIHY1SnRYek5hNTJrRHBITWFQa2RH
            R29QcGNsU25vdXI0MXFOSXJGY1ZNazAKZvRjw//IusXEM8OhKM4MZOvX3Yg7Hme7
            hJbgkrLaFFfVVEZ0SZTkIU82QlOE+V4i3mFAcp803PMoMD0wU5Ew1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVjlCNnU2ems0WStkbXVE
            M2VMbWdwN0RWcTdUSDBHLzNrUVBJaVZRMHd3CnZyZGxqbE9nN0ZLc3VDZjRIcGdu
            Q1pSN0gwcWRMSThxS0VnVGlvL3ZQYUUKLS0tIEVweExaakM1Umk1dDl6ZmVMaGx1
            MFF0eHhxcy9PVVd3MWlGVmVNZEdYVlEK3mmhCUKKnxWyuhgff9aUXrt4Mo0CNK8W
            z33bxE7R0Ik5AA6H9hFNZ9Cc52fl8q5KUvcWl2dBBLYN2obxblacQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T17:33:17Z"
    mac: ENC[AES256_GCM,data:jKs2zBS3oivQSZ8hF9hS91mBeNYAbBUl4p5xyX5TIifiqrxqN01r1CCTKpldbSGlM63joeXj8Skk0OxJAmnNyo6enKPpBkAYgBaJoawI1xBG5x0Js4wF8RBno9jYeQMEnQzdpUJuUXL3r1ZDFN8/HDjkABNgEjitcnB6PqcHUuM=,iv:JtkOZPN8/MT5YecDe8h7nW+Qo0+NLaOeGRUR/+cZ94o=,tag:PkvK1HcoQ82PDu0i7cWfxQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
