apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: epicgames-freegames
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "30"
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
    ingressClassName: traefik
    tls:
        - hosts:
            - ENC[AES256_GCM,data:wvliVxYdiRmiDDTv/nT284si/qHxUcJulBs=,iv:3L/pSAd73mVSSSwPG/kfqk5Y+7vWdoyqgBuo6P2XEx0=,tag:HTEsXhGDKo6UdcNdTMyLmQ==,type:str]
          secretName: wildcard-cloudflare-production-01
    rules:
        - host: ENC[AES256_GCM,data:QukRrAqZIF+0hphD9xOpqm20BU2ZbbATR9k=,iv:E+E+hADy1NHXY7IU/H75X7CggyTXmJSgtms1Cz1wq98=,tag:uH6B5HUtgxjUffKrESocTA==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: epicgames-freegames
                        port:
                            number: 3000
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWDA1V1dHWTJERTRmblZF
            MUw1S1RmOGdMTmdWRUZOUDdxY3BuNHQ3ZGlRClgyN1pnbVIwYVZEUXRZOFUra1Jp
            enp6emhURi80ek5Hc3h0ZUEvcG9JQ2cKLS0tIDVOckg3eVAzMUg3L0pLSnFrdkRk
            TWIyVzJkNXVIcW5CTUZWU0d0WWxacUkKvPjK+sJQPs/S05+9ev4vkjPUEJw+KxmE
            XB1GulgYzt83hALwOz9tZ0XcXFAnE3APZ5kxNSU9Tw98JDq8E/3Ibg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOENrZGwzL0kvaXFvYXFu
            MGRmSUNrQ2NMaXRzQ20weXFCNDF2TnJvb21zClZTSlFsZ3p1UElJY3dYd0hDY0dR
            amNnVDBXVTJ4V2pxaDJVb0Fyb3pZUUUKLS0tIE1GRGRGSEl1S3lCc29IckNjYTVF
            UndJeDQxOUZLcStrcTVnRVBZNURzS1UKI8a4UuyzsfPwI8mG/RjqCUVj/NeHvrm2
            x2KAc5uZozqy6/RAFOikYjoKHXEY9H3FLtxjZPJSdwPc2uNHlObt2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T16:42:43Z"
    mac: ENC[AES256_GCM,data:AoHa2bWbD6g2m65MtZ696FtgTCqQ1fOYSUwvrU+EhqolqxRiRMR4DaKaSwE7TMhSNxtUGMI3YLQ896c4GPGIdEEJJ5g9McqNnA3VNwqprOXBasKKgof+mHfY3hRiFtY0mT89hfraa+pJf//21dqVQYJOkrMx01aRsYcZ8jF+/QE=,iv:lJfutvnKMfTUrj4nPDCn3Uu4WZ227qU1VdlO4JkKEJM=,tag:UDZYBl6Qb5YK4A/At502BQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
