apiVersion: apps/v1
kind: Deployment
metadata:
  name: epicgames-freegames
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/name: epicgames-freegames
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: epicgames-freegames
  template:
    metadata:
      labels:
        app.kubernetes.io/name: epicgames-freegames
    spec:
      nodeSelector:
        node-role/workload: zfs
      strategy:
        type: Recreate
      containers:
      - name: epicgames-freegames
        image: ghcr.io/claabs/epicgames-freegames-node@sha256:2312373160001b335850dfd69b24970437dcb5695016f65b9a5f04a198e1ab77
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /usr/app/config
      volumes:
        - name: config
          hostPath:
            path: /vol_raidz1/docker/configs/epic/config
            type: Directory
