apiVersion: apps/v1
kind: Deployment
metadata:
  name: epicgames-freegames
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/name: epicgames-freegames
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: epicgames-freegames
  template:
    metadata:
      labels:
        app.kubernetes.io/name: epicgames-freegames
    spec:
      nodeSelector:
        node-role/workload: zfs
      containers:
      - name: epicgames-freegames
        image: ghcr.io/claabs/epicgames-freegames-node@sha256:f3b5640cf8757693c2cf20d2b5c558c5e84b2085bdcdddd8111974602003eb48
        ports:
          - containerPort: 3000
            name: http
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /usr/app/config
      volumes:
        - name: config
          hostPath:
            path: /vol_raidz1/docker/configs/epic/config
            type: Directory
