apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - k8s.deployment.yaml
  - k8s.service.yaml
  - k8s.np.epicgames-freegames.yaml

generators:
  - kustomize-secret-generator.yaml
