---
commonAnnotations:
  argocd.argoproj.io/sync-wave: "91"

helmCharts:
  - name: vpa
    repo: https://charts.fairwinds.com/stable
    version: 4.10.1
    releaseName: vpa
    namespace: goldilocks
    includeCRDs: true
    #valuesInline:
