clusterCollector:
    ingress:
        enabled: true
        className: traefik
        annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure239
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd
            kustomize.config.k8s.io/behavior: merge
            kustomize.config.k8s.io/needs-hash: "false"
        hosts:
            - host: ENC[AES256_GCM,data:TPutw9pTnf+qq9pZ5pTsDU6GJxcsWxbw6k80jYSUAhJhixcbLU5Rnk6EhwMmFxg=,iv:RYyYuRAEDfOkReLMebMcVq+Pv1xTza9v77Il80AaBt8=,tag:ORaZJ2dMl8l6WDM0VJBBrA==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:DA==,iv:GPinF6ewjQcXbTAUla27z3O/kY1IJHf1wR0lxVX+STc=,tag:H8eiGXlqG1z2eT7SVuSAUw==,type:str]
                  pathType: ENC[AES256_GCM,data:bRZUCXOv,iv:HqgaEcZEylZN6gMvOv51YUqC6qyby8sY6XYQ/6VRE7U=,tag:jo8tI1299N14Cj8vFvjgng==,type:str]
        tls:
            - secretName: wildcard-cloudflare-production-02
              hosts:
                - ENC[AES256_GCM,data:7Qc6BNWA896FIZ+7XG96p3ZAwV7Jmg2/gu4u+HI7saunnU77hrQop8M8XHSRWu4=,iv:4DHPJnLsJl+KB1qYFk7zwyvn2PsWSd4Tq2FUl4pMPmc=,tag:TAobL/Hi3tR32GD+0r/5dw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SzlHUTV3dWlwZnZJRFFZ
            am9KZU8vTngvZVVZZ05GODdxUTRXVWxFRVN3CjIvMWJaZXhiYUYyZ3BCaHpmallk
            U3dxK003OXZIQzNLZk9NSzZ3N0tVQjAKLS0tIGhBcXJ3NnpWNkRLV25RNk1yVVJO
            UkNqdW02VGF5RlFDeG85RmJSU08rMkEKkb8C1V8dJCkd7EzvJNnaGxx1v2L2a/Xh
            CnDu5+aPWIxndD3Hii9KBP4bMCvH4ptZW56PucZ/F/SIWjwokKGFPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RnJiZ25xNldGZTQybW5U
            Zng5RUlaRFFRWSthazJrekpaTmlyUDNDRGpnCkdieGdWUFZZTERMMy8rRkNaRDhF
            VTN3RGdHOVVIMVN4WTFjK0ZTRzBVTjQKLS0tIDZjQng4RXpudG05N1RBYUJnR09N
            TlBBOEllYUlnZU5HWlB1V1VpQ2Z0Wm8Kargm1wTGdfmc4abtu2hC/8W50Cozbs7x
            GueJre7kDSnuX66PyT0ZLE+Oka8oPN7sE+NWTPaYaxznE3wKViFrTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T12:18:29Z"
    mac: ENC[AES256_GCM,data:X5DOV0VzTNm4qgpmzpwVRkoFuAS25fQ4AY4S0LCixXVUrDRBU9dRcAX6LGmoWOeYr+V23XKMrKsVX4rg2197sxVUAmkrmf58hh5P/7GnNn0f3Zci/fANG8LNu8cBNXPP7LRC3c/5CvaCh0MSUim6Nav2Dr8tcwdyY95XDzLzDTI=,iv:f70XuDdTgcnA8Tv0T+DwUtUzGWcyx4bLY/se4db5uqI=,tag:YjU8nVvIPA9mAvSowA+EhA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
