---
resources:
  - k8s.tools.yaml
  - k8s.np.omnitools-default-deny.yaml
  - k8s.np.omnitools.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "50"

generators:
  - kustomize-secret-generator.yaml
