apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecureSkipVerify
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  insecureSkipVerify: true
