---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-internal
  namespace: kube-system
spec:
  gatewayClassName: traefik
  listeners:
    - name: web239
      protocol: HTTP
      port: 8010
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure239
      protocol: HTTPS
      port: 8444
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-cloudflare-production-02
            namespace: kube-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-external
  namespace: kube-system
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 8000
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure
      protocol: HTTPS
      port: 8443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-cloudflare-production-01
            namespace: kube-system
