apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: gostatic
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "30"
        traefik.ingress.kubernetes.io/router.entrypoints: web239,websecure239
spec:
    ingressClassName: traefik
    tls:
        - hosts:
            - ENC[AES256_GCM,data:KLF4sV0XnmYc+zHoc6CR+D5UtjI/mIEwHbz2yM6H,iv:g/Y8u7YS+DFUP/W15Vrx8vr7bJeeeKUpa4kOCBFwGK4=,tag:lDKd4VMk9zQT4fIXlgUTXA==,type:str]
          secretName: wildcard-cloudflare-production-02
    rules:
        - host: ENC[AES256_GCM,data:wMtCFSDdiXGLgmEvhVe9q7E5oZufSrdMmWhJg0od,iv:B1DWep51OHvUnbll2oleFVoTtJKeyNF/sUHnfePCByk=,tag:vSS3Nm/ckFG8PafBqKnniw==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: gostatic
                        port:
                            number: 8043
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WFlYVXVVMEdkWGFCSGZC
            d1RoZUhkT3RzRUhvYXBoNDhHaHVLMjMrZHg0CkxCQkpicFR2M0NFSG1ZSE9TeUw0
            UzB0UVJrcHozVmpMbGlZd3ZibXpKZmcKLS0tIFdONzBuZVdFdU92SDE1TWl3bGM4
            T0JPMGpycG1UcnpwQUtyZW1PVHA4Mm8KvuzMYIUKmV3J+Jf4F/f99s6rbajT3l6n
            89YMUbpk5l7buZjasHaHZLR2TEHGWJ6IDioAGaqQUalUcJOAHOVAFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSWN4bGMxUmpzUmlTWU1D
            SXprR1FmaEVtU0pRQ2ZEQW9MaFN5Rk1pOEdNCk4rU3RGRVQ1blFVR2J4T2hYK1Br
            bFUwTmh6QkhCemNoL3NVSnVHN1d1VDQKLS0tIFM4bGtZaFVVaW5qdEtCL0orSWlz
            blA2MDJlQ284UXIzWk8wYkZjakpOTjQKdVxeO4p1z3ltLpV2Ox/LVZJ+79O/OeVD
            V5itKbOdyvabyOONbOWRbX+eahfQCxZYo98lpNj+Dy2o8W6/HCkjZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T08:02:50Z"
    mac: ENC[AES256_GCM,data:Z+HZDy4FWZpfucES6VE99TvWvhLa01voPl56KRHl3pXw6/UqFDFcqq3iIMUYStLKIx7Q/6mbyeNrQaV1QnLXf9FUzo163N3WZiURbw06d3buI3BSjuqSFIenMao5AJPSfoU3OSxuha5tzV3ZkBW4zMhZSGXCMryzYFViYAZL8Fc=,iv:8IUAEv4CaW0dI3+0gdbUsqIlUkoCtFWW8aR3BCY6kdA=,tag:t9wAHN8Z/iKV5sMGeAj7zw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
