apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nzbget
    namespace: downloader
    annotations:
        argocd.argoproj.io/sync-wave: "30"
        traefik.ingress.kubernetes.io/router.entrypoints: web239,websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd, authelia-forwardauth-authelia-basic-forward-auth@kubernetescrd
spec:
    ingressClassName: traefik
    tls:
        - hosts:
            - ENC[AES256_GCM,data:k54RHsxNIwi9MlNoNA3t6wt7V48hyZSHeGBYqw==,iv:sahgkqH837N+4nJjKcVvn6/bOt1bZt+Sa3DBMwf0u3Y=,tag:RDLQuQP+uj5zmYwRZGv6Ug==,type:str]
          secretName: wildcard-cloudflare-production-02
    rules:
        - host: ENC[AES256_GCM,data:G+OrMtk5LnQl72GTdN8++X8Ldlyngo3iIgs18w==,iv:t0/cmH1qyxgHo6cCV64xWRCVQRGqcULhAiYlIrO6J/0=,tag:4wLscAAK0IQBv8yiDYW/ug==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: nzbget
                        port:
                            number: 6789
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUmlDRjlvbm95ZVdpaDFC
            MkI2dGlvemdsVHNHdHRxMlAzc1NEK29UU1Q4CmRUbFZQeUR6Z2dDRks1cmJXRHlk
            WjV6eWdGVW9FS1VjcTdIeGZtRFJ5U1EKLS0tIG5qRTcxVzJYQzNyaVNCUHo2MEVr
            c3pmTUtvWVFnN3JBZkhEM1ZSczMzWEEKx6JqqRier72Wuon6evqISrFg5+IGieLr
            YRyAuU+IFOcNHAOo3Qub7P98ax+i3xCFlWeoK+MFxdter0C/kLo9Yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL2pNRzFxaEYraHM3SzFn
            Y1Jjc0VXUlpRZlJjbjY5Tjl0VG1BSytsR3o4Ci9nZk5sSGJVdFdUT0F4dGg4MlBa
            Smt5eTVJYkcyQVloUmpCbGtsdFZZMjAKLS0tIHU3MktrUGFmeGtDaHhWQ0xBQzVz
            cWZvemNRTTE4bjJ6UzJjOHFrQktHRG8KXDCy9NO9smQL4M7hqmQYHkyrZ21VzBMY
            6jBlDMIpMijLj459VabNFrVRWpfA0lW25X9qhgUoDH236ZyC9ZQhLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-06T17:37:46Z"
    mac: ENC[AES256_GCM,data:goR/ZvXrfB0Ba7rE6mEu8aTfsnQ2Ho2c4Q//0qbN4UkJU+ciNgm+Bp2uQd/uVleJCWa4/om+LZeQEuGTgTLcaXdHHjuldo7sAWbZsrJ6RHJijjyHxkJB8mIfu6UUJ8Rqnupa+PcSqdTb3AatNMDCc2WBCeJGneYEWkXftdjRI2Q=,iv:ofX5P9Su3UIwY8TTThfTrvcuRusbRxe7zB0uvzfar/k=,tag:clJ8zSa2RV6fcLF2ine57w==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
