apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: downloader
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/name: nzbget
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
    spec:
      nodeSelector:
        node-role/workload: zfs
      containers:
      - name: nzbget
        image: forge.geekbundle.org/madic/docker-nzbget@sha256:a0e1f0ccf0ca2f93ec8c81581910bc036746270276697a526ca8f3bb2d5657ab
        env:
          - name: PUID
            value: "0"
          - name: PGID
            value: "1002"
          - name: TZ
            value: "Europe/Berlin"
        ports:
          - containerPort: 6789
            name: http
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /config
          - name: scripts
            mountPath: /app/nzbget/scripts
            readOnly: true
          - name: video
            mountPath: /vol_raidz1/video
          - name: music
            mountPath: /vol_raidz1/music
          - name: photo
            mountPath: /vol_raidz1/photo
          - name: downloads
            mountPath: /vol_raidz1/downloads
      volumes:
        - name: config
          hostPath:
            path: /vol_raidz1/docker/configs/downloader/nzbget/config
            type: Directory
        - name: scripts
          hostPath:
            path: /vol_raidz1/docker/configs/downloader/nzbget/scripts
            type: Directory
        - name: video
          hostPath:
            path: /vol_raidz1/video
            type: Directory
        - name: music
          hostPath:
            path: /vol_raidz1/music
            type: Directory
        - name: photo
          hostPath:
            path: /vol_raidz1/photo
            type: Directory
        - name: downloads
          hostPath:
            path: /vol_raidz1/downloads
            type: Directory
