apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nzbget
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "30"
        traefik.ingress.kubernetes.io/router.entrypoints: web239,websecure239
spec:
    ingressClassName: traefik
    tls:
        - hosts:
            - ENC[AES256_GCM,data:xMPoRdtMpQpvjWjaa7TiukMIHuil68A9clRHZQ==,iv:FF9Ai+At17nr+09iDhL1ndnnkOsBSr8dJLW8yr9vrHA=,tag:M3RahIim9mjCqMWEqGusjw==,type:str]
          secretName: wildcard-cloudflare-production-02
    rules:
        - host: ENC[AES256_GCM,data:UWoaFUK+vB1uSUd5PkAiLa/m956b8NRqsLozIQ==,iv:lIRqa/l78AnKbyt0G9sooedb4VHE/fBTr8P03MPGo1A=,tag:LJpPU109zyLz00iHvXAfGA==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: nzbget
                        port:
                            number: 6789
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M3g3ZDZiVXJsYmpGeHhu
            eEhXUkNwMTZKSFRpMEV4NGFKRjFXZzZJZm1nCm4rUkVxK3hjVDJMUTZCb0xEQTJz
            K01uV2hpRmV2TXNPbkRPRStrT2kyY2sKLS0tIFpWbTVZWTNrTDVMS1paTlZQSkNM
            bWRwM0k0NXZZMGhDOGpiNk5SLzdsdm8KDYqgsw7XBSCkFH6RpKC/AaK/+JP9CS8i
            m2e2sxDOIHMSF93tnKuZ5sy7I3XU6An50fyq57jimdmaonwH5Uz+YA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSmRRYVB4S3N6am12V3ha
            a2xHOWFaaHhMNGZMNXRPYWMrRUxEMDlIWlh3ClVLbXFmTmRQWmJjTEdpSCtPaVR2
            V2NaNm1YK1ZGNW9BTXNiSDJUUnllVTgKLS0tIEpXbzNUekx5OVpTdHNOWXB2akpE
            b2hMZjBXaVBsNGtYN3E3aG9sNGJnMm8K7V0xO1eOLqBdbW8ESqjUOfW0caPuZGdd
            Baw9vPbC3evlb70t0Sv27N+w2x0erLtbayXVsaZR1Sf22FjoyF7/HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T08:10:39Z"
    mac: ENC[AES256_GCM,data:bufPGvS80Re549itoUT9dpDytdc/7Pb7fBorFm8+X8HtWje9X+Shlaf5jM2iV29cea48l/GLJV3IDkZTOK8j7LJWVq+JoTnkcLxjktBX64U5s/Lqv9rMHfQJP8qaZ5WOZLyc2tRcqXHX3DyQWONV3SSphGNklbCrDSbxylAUsew=,iv:wvIi3IluXHEYtU9eYqVSaBOUQKM8xyCQl4mzznEb+/c=,tag:AI8GUQ3tJWzPeHNQBhy6/A==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
