---
# https://github.com/rancher/system-upgrade-controller/releases

resources:
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.18.0/system-upgrade-controller.yaml
  - https://github.com/rancher/system-upgrade-controller/releases/download/v0.18.0/crd.yaml
  - k8s.np.system-upgrade-controller.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "96"
