apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: radarr
    namespace: downloader
    annotations:
        argocd.argoproj.io/sync-wave: "30"
        traefik.ingress.kubernetes.io/router.entrypoints: web239,websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd,authelia-forwardauth-authelia-basic-forward-auth@kubernetescrd
spec:
    ingressClassName: traefik
    tls:
        - hosts:
            - ENC[AES256_GCM,data:Xxz8G16WgpIADmD/tXDiWNhVgltDx8GtcCMOXA==,iv:pcaPQ8rkw+VVng/UgHewrKR7pSgVowMB1pXrSHGv52Q=,tag:y3GIQ+BHXam8eKntWTTXDQ==,type:str]
          secretName: wildcard-cloudflare-production-02
    rules:
        - host: ENC[AES256_GCM,data:g5tPr6UhmmOTIyZvylC0CBzXrDQryBhMRLJMhg==,iv:ADwsROhMUqZ/JXTCc9mA8ewdibD1RM+yXSfy8Wz5l1g=,tag:q+FK+MgkzEFy9oOZRmclrA==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: radarr
                        port:
                            number: 7878
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUVzV284cWtSam9SdjNj
            WDBTTVV2WERtam5uSVFta1hKM01xa3BPVmo4CnlNUStQRTFINEVIN0Iwd2xWem1K
            NnZrT21MR2h4S3d6NXVQKzVlTzdsdEkKLS0tIEtDNDRxdVpBZjljYmZYWTdxTlR3
            OEY0WEkrTUsvTnpoaHphbmlHVE9jaFUKT7GiACjqqB8yTXLnleI7My4maG/1CmoG
            Px4OOFt956oUtw8pl+l68IqIQJWDwdrdZH/qVqCJOPJQNaqvh2So9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZGJtZmZtNE9XZy9aeVpY
            R2xFTnlTT2k5U2tIdTlBd1pvVWFDVEJicHk4CjVhcXIxcTFqTi9pTTA3UUFGRlVO
            dm4yd2p2SnR3S0s0dlBTVFBHNHZ6L1UKLS0tIDkvVENxYWlsbGZFR2VXZU81TVE2
            MEhhL09rbFR6bmduSjFCZS8rTUUzc2sKGq0JYweTh21SaKNwEE6cDDH04OpWsX29
            1Lmx1VFK7zjTfO8A0LgYMSocPJCxP5mBcIEFb6Q0RuEBULbb0a7kGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T08:22:09Z"
    mac: ENC[AES256_GCM,data:7tFUHIjQG9/VAGG/UkzifG+QETQigDjyMDqN0as1ZRtSBw2uLe22uNlNfCoX3JXMuyY9HcEbQ4lMXEHn+9GkTAKcU5uqVQazhtw9FlCoOijmBzT/Z8iHh8J5OnevAhkrNUzFv/ADpfH2ID+QqDmxSZqhU+mje5NCvQCMP1AKTBo=,iv:dwBzkJG/AftfzJJeYNuQ5pKVeThmBsWR9/T931pXUeo=,tag:cAEFt0FZvumeGGoVtetmhw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
