apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: downloader
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/name: radarr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      nodeSelector:
        node-role/workload: zfs
      containers:
      - name: radarr
        image: forge.geekbundle.org/madic/docker-radarr@sha256:ae9e24c887a4be727af1e631a833faa3c418f10a544a2339076b80297d799bb4
        env:
          - name: PUID
            value: "0"
          - name: PGID
            value: "1002"
          - name: TZ
            value: "Europe/Berlin"
        ports:
          - containerPort: 7878
            name: http
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /config
          - name: video
            mountPath: /vol_raidz1/video
          - name: music
            mountPath: /vol_raidz1/music
          - name: photo
            mountPath: /vol_raidz1/photo
          - name: downloads
            mountPath: /vol_raidz1/downloads
          - name: trailer-config
            mountPath: /opt/Trailer-Downloader/settings.ini
            subPath: settings.ini
            readOnly: true
      volumes:
        - name: config
          hostPath:
            path: /vol_raidz1/docker/configs/downloader/radarr/config
            type: Directory
        - name: video
          hostPath:
            path: /vol_raidz1/video
            type: Directory
        - name: music
          hostPath:
            path: /vol_raidz1/music
            type: Directory
        - name: photo
          hostPath:
            path: /vol_raidz1/photo
            type: Directory
        - name: downloads
          hostPath:
            path: /vol_raidz1/downloads
            type: Directory
        - name: trailer-config
          hostPath:
            path: /vol_raidz1/docker/configs/downloader/Trailer-Downloader-Config
            type: Directory
