apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: downloader

resources:
  - k8s.deployment.yaml
  - k8s.service.yaml
  - k8s.np.radarr.yaml

generators:
  - kustomize-secret-generator.yaml
