apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbhydra2
  namespace: downloader
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/name: nzbhydra2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbhydra2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbhydra2
    spec:
      nodeSelector:
        node-role/workload: zfs
      containers:
      - name: nzbhydra2
        image: linuxserver/nzbhydra2:8.3.0
        env:
          - name: PUID
            value: "0"
          - name: PGID
            value: "1002"
          - name: TZ
            value: "Europe/Berlin"
        ports:
          - containerPort: 5076
            name: http
            protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /config
          - name: downloads
            mountPath: /downloads
      volumes:
        - name: config
          hostPath:
            path: /vol_raidz1/docker/configs/downloader/nzbhydra2/config
            type: Directory
        - name: downloads
          hostPath:
            path: /vol_raidz1/docker/configs/downloader/nzbhydra2/downloads
            type: Directory
