apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: nzbhydra2
    namespace: media
    annotations:
        argocd.argoproj.io/sync-wave: "30"
        traefik.ingress.kubernetes.io/router.entrypoints: web239,websecure239
spec:
    ingressClassName: traefik
    tls:
        - hosts:
            - ENC[AES256_GCM,data:RhuXySfp/vGMZ5PkhrcIFkzEw5io0sIKj6/Ua0w/oQ==,iv:YnNSlfPKyucOTmZTVQtnJC6iazxnyWSuaH63oDDf7CE=,tag:6tZT7GOdspukY+LChEZ5Pg==,type:str]
          secretName: wildcard-cloudflare-production-02
    rules:
        - host: ENC[AES256_GCM,data:BQSZSzODVX7pPIBouEbrSVLVUj2TpfgrnFZQpMrtBw==,iv:PBQkwz+3VAisFcECgfCw4Zk99jsIw/LlmPPrF/aNo8M=,tag:JgzghbjbooNszt2nwAT6yA==,type:str]
          http:
            paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                        name: nzbhydra2
                        port:
                            number: 5076
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubDUwL2RFcG5pTkhCNWRU
            Tm1oWXBQQjRneUhtRW1CSHpxKzRnTkx3YW1RCmRkV0d3Szk0QVc4QVRFQ3RSRklM
            cWRobmd5aFdkUWlFOVdibmlEemF3TGcKLS0tIGprYytBMXJNQzFMRmlVRjB3RlNJ
            STBnM1ZCT0ljOHNZTjRKZE4xUGZZK3cKohfkG7r1LnwRQ8wIgaDjwohez2A6JBHV
            QIKU+PInmkESwQSYgkt5bmQy2Zfjjp6TI62HWtFiZSo+AYXt0zFOYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZGhiZ0QzVks3aytRNitM
            dmFubS9mUUFQbXE4Q1Npb0FmY1c4TWxidFdRCjRCK2V2VzRlOERjVFpwZFprOWFI
            eEFtcE5aZlNHempEWVY5Q2Z6SXB0ZTgKLS0tIElDaVN0cXpzNDk5elBCbXVoYk9w
            S2dWbHF4TEZ2bTF5eWJYdjlHU0lKVm8KvuVZYeuO+yJl4M/YyY1bC+ycpNHkkcYd
            Mabji27T5tAM4eT8AO1tEtTku57CqYpCF/2mf7pZJHk5M0SsUAhy6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T08:10:31Z"
    mac: ENC[AES256_GCM,data:EtUKh/QtJr1w+9A/iIlvyqYOKi31IRprScsyvhSW0p0l54gaY8pMgAPrjLurKeE8y/gsbb93T7fBj2jX3AGbX8R6QV/mb08wnYE9VANl5MH9qBpmX7WyOxusyaliW21LKu2N1xZ4V3TrYbEHLy/a7CkaCCiYr8TtIgCLKN/Dx80=,iv:PTwbs1+8vN9I7neyv9R5XGNHe5Vw90+srA1lQHAIg74=,tag:pMTQKSeIgSs7LTelmK67qA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
